### PR TITLE
Add lazy static to regex

### PR DESCRIPTION
**Pull request by nicosuave**
I did this so that the same regex can be reused in iterations

### CODE REVIEW

**Comment by cyphactor** [comment]
@nicosuave looking at this now I am not sure that the lazy static calls should be happening where you put them. It seems like from their examples they should be done outside and then they should just be accessed where you currently have them.

**Comment by nicosuave** [comment]
@cyphactor the [regex crate example](https://doc.rust-lang.org/regex/regex/index.html#example-avoid-compiling-the-same-regex-in-a-loop) uses the lazy static inside the function definition. I prefer this style, as it makes the function self-contained.

copy pasta from the above link
```rust

fn some_helper_function(text: &str) -> bool {
    lazy_static! {
        static ref RE: Regex = Regex::new("...").unwrap();
    }
    RE.is_match(text)
}
```

**Comment by cyphactor** [comment]
Hmm, must be even more magic going on than I thought.

**Comment by nicosuave** [comment]
✨

**Pull request merged**
