### PR TITLE
Add Arch Linux installation instructions to README

### PR DESCRIPTION
**Pull request by wezm**

### CODE REVIEW

**Comment by cyphactor** [comment]
Hey @wezm, thanks so much for the contribution. Sorry, it has taken me so long to get to this. I was on vacation and didn't have internet access.

**Comment by cyphactor** [comment]
Looking at the PKGBUILD file contents I don't see how it manages versioning. Other build systems I am familiar with that support git as sources generally have a sha that is tied to the version in the package description. Is there not a similar feature in this?

```
# Maintainer: Wesley Moore <wes@wezm.net>
_pkgname=alt
pkgname=${_pkgname}-git
pkgver=103
pkgrel=1
pkgdesc='Command line utility that attempts to find the "alternate path" for the provided path'
arch=('i686' 'x86_64')
url="https://github.com/uptech/alt"
license=('MIT')
depends=()
makedepends=('rust' 'cargo' 'git')
source=("git+https://github.com/uptech/alt.git")
md5sums=('SKIP')

pkgver() {
    cd "$srcdir/$_pkgname"
    git rev-list --count HEAD
}

package() {
    cd "$srcdir/$_pkgname"
    cargo build --release
    install -Dm755 "$srcdir/$_pkgname/target/release/$_pkgname" "$pkgdir/usr/bin/$_pkgname"
    #install -Dm644 "$srcdir/$_pkgname/contrib/man/$_pkgname.1" "$pkgdir/usr/share/man/man1/$_pkgname.1"
}
```

**Comment by wezm** [comment]
You're right, as it is now it will build current master at build time. It's on my TODO list to tweak it to track releases instead of master. Happy for you to hold off on merging until that's done if you want.

**Comment by cyphactor** [comment]
Yeah let's wait until you add support for the versions. Also I just release v2.4.0 which includes a man page so you should probably also add support for that. 

The only other question I had was around the AUR repository being named alt-git instead of alt. Is there a reason for this? If so what is it?

**Comment by wezm** [comment]
It's conventional for the package to be called <package>-git when it's being built from master. I'll replace this package with one just called alt when I do it based on releases.

**Comment by cyphactor** [comment]
Awesome, thx.

**Comment by cyphactor** [comment]
@wezm I am going to close this PR for the time being. Once you make the necessary changes please reopen this pull request.

**Pull request closed without merging**
