### PR TITLE
Add Arch Linux installation instructions to README

### PR DESCRIPTION
**Pull request by wezm**
This picks up where #14 left off. I've now [added a PKGBUILD to the AUR](https://aur.archlinux.org/packages/alt/) that builds the current release.

### CODE REVIEW

**Comment by cyphactor** [comment]
@wezm I pulled down the PKGBUILD and reviewed it, it looks good. I tried spinning up an Arch Linux Docker container but soon ran into issues with it not letting me run `makepkg` as root. Then after creating a user account and switching to that user account I ran into issues not having some binary to strip binaries, etc, and not having sudo to escalate use privs.

Do you have any recommendations for Arch Linux docker images that would potentially be setup in the proper way to be able to install a package this way? Apparently this Docker Image isn't https://hub.docker.com/r/base/archlinux/

I would really like to have a development process we can standards, document, and use to test the packaging for any distributions we officially support.

**Comment by wezm** [comment]
Hmm no sorry I don't have any recommendations for a Docker image. I've only run Arch on my actual machines not in a container. If it's not already present, installing the `base-devel` group might help ensure all necessary dev tools are installed. Additionally the docker image will need cargo and rust. So you might add a `pacman -Syu base-devel cargo` somewhere in the container build file.

**Comment by cyphactor** [comment]
@wezm thx for the guidance. With that I was able to get running and setup a Docker Image to test it. You can checkout the [source](https://github.com/uptech/alt-archlinux-builder) and that published [Docker Image](https://hub.docker.com/r/uptechworks/alt-archlinux-builder/).

This made it possible for me to successfully test the packaging you put together.

Thanks again for the helping making alt more accessible.

**Comment by wezm** [comment]
Excellent, glad to help and thanks for merging.

**Pull request merged**
